FX2LIBDIR=../../
BASENAME = uart_main
SOURCES=uart_main.c 
PID=0x1004
CODE_SIZE = --code-size 0x3000
XRAM_LOC = --xram-loc 0x3200 
XRAM_SIZE = --xram-size 0x700
INT2JT =
DSCR_AREA=
include $(FX2LIBDIR)lib/fx2.mk



